# Generated by Django 2.0 on 2018-08-28 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spotify_to_gpm_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifylibrary',
            name='user_id',
        ),
        migrations.AddField(
            model_name='spotifylibrary',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spotifylibrary',
            name='library_name',
            field=models.CharField(max_length=100),
        ),
    ]
