# Generated by Django 2.0 on 2018-08-29 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_to_gpm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPMLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GPMPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=100)),
                ('playlist_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GPMTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=100)),
                ('artist_name', models.CharField(max_length=100)),
                ('album_name', models.CharField(max_length=100)),
                ('store_id', models.CharField(max_length=100)),
                ('library', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spotify_to_gpm_app.GPMLibrary')),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spotify_to_gpm_app.GPMPlaylist')),
            ],
        ),
        migrations.AlterField(
            model_name='gpmuser',
            name='spotify_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='GPMUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gpmplaylist',
            name='gpm_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_to_gpm_app.GPMUser'),
        ),
        migrations.AddField(
            model_name='gpmlibrary',
            name='gpm_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spotify_to_gpm_app.GPMUser'),
        ),
    ]
