# Generated by Django 2.0 on 2018-08-28 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_to_gpm_app', '0002_auto_20180828_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifylibrary',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
