# Generated by Django 2.0 on 2018-09-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_to_gpm_app', '0002_auto_20180829_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpmtrack',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='spotifytrack',
            name='playlist',
        ),
    ]
