# Generated by Django 2.0 on 2018-08-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_to_gpm_app', '0003_auto_20180828_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifylibrary',
            name='userr_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
