# Generated by Django 2.0 on 2018-08-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_to_gpm_app', '0004_spotifylibrary_userr_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifylibrary',
            name='user',
        ),
        migrations.RemoveField(
            model_name='spotifylibrary',
            name='userr_id',
        ),
        migrations.AddField(
            model_name='spotifylibrary',
            name='user_id',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
