# Generated by Django 2.0 on 2018-09-19 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spotify_to_gpm_app', '0004_auto_20180919_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpmuser',
            name='spotify_user',
        ),
        migrations.AddField(
            model_name='gpmuser',
            name='spotify_user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='GPMUser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
